apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: waserkarim/ultimate-cicd
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/image-tag-update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/waseralkarim/JenkinsProject-EndToEnd-CICD.git
    targetRevision: master
    path: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
