apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: waserkarim/ultimate-cicd
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/image-tag-update-strategy: semver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: waserkarim/ultimate-cicd:replaceImageTag
          ports:
            - containerPort: 8080
